
name: CI

on: [ push ]

# -${{ hashFiles('**/lockfiles') }}  

# export GYP_GENERATORS="ninja"
# export GYP_DEFINES="build_with_libjingle=1 build_with_chromium=0 libjingle_objc=1 OS=ios target_arch=ia32"
# export GYP_GENERATOR_FLAGS="$GYP_GENERATOR_FLAGS output_dir=out_ios"
# export GYP_CROSSCOMPILE=1


jobs:

  macos:

    runs-on: macos-latest    
    steps:

    - name: clone depot_tools
      working-directory: webrtc-checkout
      run: |
        git clone --quiet --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git
        echo "::add-path::$(pwd)/depot_tools"
        mkdir webrtc-checkout

    - name: fetch
      working-directory: webrtc-checkout
      run: fetch --nohooks webrtc_ios

    - name: sync
      working-directory: webrtc-checkout
      run: gclient sync

    - name: generate build
      working-directory: webrtc-checkout/src
      run: gn gen out/Default "--args=is_component_build=false is_debug=false symbol_level=0"
      #  "--args=enable_iterator_debugging=false is_component_build=false is_debug=false symbol_level=1 "

    - name: introspect build
      working-directory: webrtc-checkout/src
      run: gn args out/Default --list
      
    - name: build
      working-directory: webrtc-checkout/src
      run: ninja -C out/Default 
      # field_trial_default protobuf_lite p2p base jsoncpp

    - name: package
      working-directory: webrtc-checkout/src/out/Default
      run:  |
        ls -lah
        du -sh *
        tar -zvcf ~/source.tar.gz .
        ls -lah ~/source.tar.gz

    - uses: actions/upload-artifact@v2
      with:
        name: source
        path: ~/source.tar.gz
