
name: CI

on: [push]

jobs:
  macos:
    runs-on: macos-latest    
    steps:
    - name: clone depot_tools
      run: |
        git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git
        echo "::add-path::$(pwd)/depot_tools"
        mkdir -p webrtc-checkout       
    - name: fetch
      working-directory: webrtc-checkout
      run: fetch --nohooks webrtc
    - name: sync
      working-directory: webrtc-checkout
      run: gclient sync
    - name: generate build
      working-directory: webrtc-checkout
      run: gn gen out/Default
    - name: build
      working-directory: webrtc-checkout
      run: ninja -C out/Default
