
name: CI

on: [ push ]

# -${{ hashFiles('**/lockfiles') }}  

# export GYP_GENERATORS="ninja"
# export GYP_DEFINES="build_with_libjingle=1 build_with_chromium=0 libjingle_objc=1 OS=ios target_arch=ia32"
# export GYP_GENERATOR_FLAGS="$GYP_GENERATOR_FLAGS output_dir=out_ios"
# export GYP_CROSSCOMPILE=1


jobs:

  macos:

    runs-on: macos-latest    
    steps:

    - name: clone depot_tools
      run: |
        git clone --quiet --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git
        echo "::add-path::$(pwd)/depot_tools"
        mkdir webrtc-checkout

    - name: fetch
      working-directory: webrtc-checkout
      run: fetch --nohooks webrtc_ios

    - name: sync
      working-directory: webrtc-checkout
      run: gclient sync

    - name: generate build
      working-directory: webrtc-checkout/src
      run: gn gen out/Default '--args=enable_iterator_debugging=false is_component_build=false is_debug=false symbol_level=1 mac_deployment_target="10.15.0" mac_min_system_version="10.15.0" mac_sdk_min="10.15" proprietary_codecs=true rtc_build_examples=true rtc_include_ilbc=false rtc_opus_variable_complexity=true'

    - name: introspect build
      working-directory: webrtc-checkout/src
      run: gn args out/Default --list
      
    - name: build
      working-directory: webrtc-checkout/src
      run: ninja -C out/Default 

    - name: upload WebRTC.framework artifact
      uses: actions/upload-artifact@v2
      with:
        name: WebRTC.framework
        path: webrtc-checkout/src/out/Default/WebRTC.framework/
